version: "3"

services:
  ariang:
    build:
      context: .
      args:
        ARIANG_VERSION: 1.3.13
    ports:
      - 8080:8080
#    volumes:
#      - /DOWNLOAD_DIR:/aria2/data
#      - /CONFIG_DIR:/aria2/conf
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=secret
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=123456
    restart: always