name: Docker image build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_image:
    name: Build docker image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - name: Fetch latest github release
        run: |
          THIS_REPO=https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest
          TARGET_REPO=https://api.github.com/repos/mayswind/AriaNg/releases/latest
          echo "current=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $THIS_REPO | jq -r '.tag_name')" >> $GITHUB_OUTPUT
          echo "target=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $TARGET_REPO | jq -r '.tag_name')" >> $GITHUB_OUTPUT
        id: releases

      - name: Set up Docker Buildx
        if: steps.releases.outputs.current != steps.releases.outputs.target
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.releases.outputs.current != steps.releases.outputs.target
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        if: steps.releases.outputs.current != steps.releases.outputs.target
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.releases.outputs.target }}
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
          build-args: |
            ARIANG_VERSION=${{ steps.releases.outputs.target }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}


      - name: Create new Github release
        if: steps.releases.outputs.current != steps.releases.outputs.target
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.releases.outputs.target }}
          name: Update to AriaNg ${{ steps.releases.outputs.target }}
